export const CSS = `
*{box-sizing:border-box}
button,textarea{font:inherit}
.fb-host{position:fixed;inset:0;z-index:2147483000;pointer-events:none;font-family:"Karen Instrument Sans","Avenir Next",Avenir,sans-serif;color:#2b1b2e;
  --plum:#2b1b2e;--cream:#fff8ef;--paper:#fffcf8;--persimmon:#e95d3f;--persimmon-dark:#cc4930;--lilac:#b7a1c6;--muted:#786c7c;--line:#eadfe7}
.fb-capture{position:fixed;inset:0;z-index:0;pointer-events:auto;cursor:crosshair;touch-action:none;background:transparent}
.fb-capture.off{pointer-events:none}
.fb-overlay{position:fixed;inset:0;z-index:1;pointer-events:none}
.fb-highlight,.fb-selection{position:fixed;display:none;pointer-events:none;border:2px solid var(--persimmon);background:rgba(233,93,63,.08);border-radius:8px;box-shadow:0 0 0 1px rgba(255,255,255,.7) inset}
.fb-selection{border-style:dashed;background:rgba(183,161,198,.14)}
.fb-selection.dragging{display:block}
.fb-spotlight{position:fixed;display:none;pointer-events:none;border:2px solid var(--persimmon);border-radius:10px;box-shadow:0 0 0 100vmax rgba(43,27,46,.46),0 0 0 4px rgba(233,93,63,.16)}
.fb-pin{position:fixed;width:23px;height:23px;margin:-11.5px 0 0 -11.5px;background:var(--persimmon);color:#fff;border:2px solid var(--cream);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:700;box-shadow:0 4px 12px rgba(93,35,28,.28);animation:fb-pin-in .2s cubic-bezier(.23,1,.32,1)}
@keyframes fb-pin-in{from{opacity:0;transform:scale(.72)}70%{transform:scale(1.05)}to{opacity:1;transform:none}}
.fb-widget{position:fixed;z-index:5;pointer-events:auto}.fb-widget.pos-br{right:22px;bottom:22px}.fb-widget.pos-bl{left:22px;bottom:22px}
.fb-bubble{position:relative;width:58px;height:58px;border:1px solid rgba(43,27,46,.12);border-radius:50%;display:flex;align-items:center;justify-content:center;background:var(--cream);color:var(--plum);box-shadow:0 12px 34px rgba(43,27,46,.24);cursor:pointer;transition:transform .16s cubic-bezier(.23,1,.32,1),box-shadow .16s ease}
.fb-bubble:hover{transform:translateY(-2px);box-shadow:0 16px 40px rgba(43,27,46,.28)}.fb-bubble:active{transform:scale(.97)}.fb-bubble .fb-karen-mark{width:44px;height:44px;border-radius:50%;object-fit:cover;display:block}
.fb-bubble.has-review::after{content:attr(data-count);position:absolute;top:-4px;right:-4px;min-width:20px;height:20px;padding:0 5px;border-radius:999px;display:flex;align-items:center;justify-content:center;background:var(--persimmon);color:#fff;border:2px solid var(--cream);font-size:10px;font-weight:700;box-shadow:0 3px 8px rgba(43,27,46,.25)}
.fb-bubble.starting{cursor:wait}.fb-spinner{width:22px;height:22px;border:2px solid rgba(43,27,46,.18);border-top-color:var(--persimmon);border-radius:50%;animation:fb-spin .8s linear infinite}@keyframes fb-spin{to{transform:rotate(1turn)}}
.fb-pill{position:fixed;z-index:5;display:none;align-items:center;gap:8px;padding:6px 9px 6px 4px;border-radius:999px;background:rgba(43,27,46,.94);backdrop-filter:blur(18px) saturate(140%);color:#fff;border:1px solid rgba(255,248,239,.15);box-shadow:0 14px 40px rgba(43,27,46,.3);pointer-events:auto}
.fb-pill.dragging{box-shadow:0 22px 58px rgba(43,27,46,.38)}
.fb-hgrip,.fb-pctl,.fb-mopt{border:0;background:transparent;color:inherit;cursor:pointer}.fb-hgrip{width:22px;height:30px;padding:0;border-radius:8px;color:rgba(255,255,255,.48);display:grid;place-items:center;cursor:grab}.fb-hgrip:hover{color:#fff;background:rgba(255,255,255,.08)}.fb-hgrip:active{cursor:grabbing}.fb-hgrip svg{width:12px;height:18px}
.fb-mswitch{position:relative;display:inline-flex;padding:3px;border-radius:999px;background:rgba(255,255,255,.1)}.fb-mknob{position:absolute;inset:3px auto 3px 3px;width:calc(50% - 3px);border-radius:999px;background:var(--cream);box-shadow:0 1px 3px rgba(0,0,0,.25);transition:transform .2s cubic-bezier(.23,1,.32,1)}.fb-mswitch.text .fb-mknob{transform:translateX(100%)}
.fb-mopt{position:relative;z-index:1;width:30px;height:26px;display:grid;place-items:center;border-radius:999px;color:rgba(255,255,255,.6);padding:0}.fb-mopt svg{width:15px;height:15px}.fb-mswitch:not(.text) .fb-mopt-v,.fb-mswitch.text .fb-mopt-t{color:var(--plum)}
.fb-dot{width:9px;height:9px;border-radius:50%;background:var(--lilac)}.fb-pill.listening .fb-dot{background:#ff7863;animation:fb-pulse 1.5s infinite}.fb-pill.paused .fb-dot{background:#e6b65c}.fb-pill.text .fb-dot{background:var(--lilac)}
@keyframes fb-pulse{70%{box-shadow:0 0 0 8px rgba(255,120,99,0)}0%{box-shadow:0 0 0 0 rgba(255,120,99,.45)}}
.fb-time{font-size:13px;font-weight:650;font-variant-numeric:tabular-nums}.fb-mode-label,.fb-pstate{font-size:10px;font-weight:700;letter-spacing:.065em;text-transform:uppercase;color:#dccfe3}.fb-pstate{color:#f3cc80}.fb-vsep{width:1px;align-self:stretch;margin:3px 0;background:rgba(255,255,255,.16)}
.fb-pctl{display:inline-flex;align-items:center;gap:5px;padding:6px 8px;border-radius:999px;font-size:12px}.fb-pctl:hover{background:rgba(255,255,255,.12)}.fb-pctl:active{transform:scale(.96)}.fb-pctl svg{width:14px;height:14px}.fb-clear{color:rgba(255,255,255,.6)}.fb-clear:hover{color:#ffd1c9;background:rgba(233,93,63,.2)}
.fb-end{position:relative;padding-right:10px}.fb-review-count{position:absolute;right:-5px;top:-7px;min-width:17px;height:17px;padding:0 4px;border-radius:999px;display:none;align-items:center;justify-content:center;background:var(--persimmon);color:#fff;border:2px solid var(--plum);font-size:9px;font-weight:700}.fb-review-count.show{display:flex;animation:fb-count .14s cubic-bezier(.23,1,.32,1)}@keyframes fb-count{from{opacity:.7;transform:scale(.88)}to{opacity:1;transform:none}}
.fb-tip{position:fixed;z-index:9;pointer-events:none;padding:5px 9px;border-radius:7px;background:var(--plum);color:#fff;font-size:11px;white-space:nowrap;opacity:0;transform:translateY(3px);transition:opacity .12s ease,transform .12s ease;box-shadow:0 6px 20px rgba(43,27,46,.3)}.fb-tip.show{opacity:1;transform:none}
.fb-confirm{position:fixed;inset:0;z-index:8;display:none;align-items:center;justify-content:center}.fb-confirm.open{display:flex}.fb-confirm-back{position:absolute;inset:0;background:rgba(43,27,46,.48);pointer-events:auto}.fb-confirm-box{position:relative;width:340px;max-width:calc(100vw - 32px);padding:20px 22px;border-radius:16px;background:var(--paper);pointer-events:auto;box-shadow:0 24px 70px rgba(43,27,46,.35);animation:fb-modal .2s cubic-bezier(.23,1,.32,1)}@keyframes fb-modal{from{opacity:0;transform:scale(.96) translateY(5px)}}
.fb-confirm-title{font-size:16px;font-weight:700;margin-bottom:6px}.fb-confirm-msg{font-size:13px;line-height:1.5;color:var(--muted);margin-bottom:18px}.fb-confirm-row{display:flex;justify-content:flex-end;gap:9px}
.fb-confirm button,.fb-cfoot button{border-radius:9px;padding:8px 13px;cursor:pointer}.fb-confirm-cancel,.fb-ccancel{border:1px solid var(--line);background:transparent;color:var(--plum)}.fb-confirm-ok{border:0;background:var(--persimmon);color:#fff;font-weight:650}
.fb-composer{position:fixed;z-index:6;width:290px;max-width:calc(100vw - 24px);display:none;overflow:hidden;border:1px solid var(--line);border-radius:15px;background:var(--paper);color:var(--plum);box-shadow:0 18px 48px rgba(43,27,46,.24);pointer-events:auto;cursor:auto;transform-origin:left center}.fb-composer.open{display:block;animation:fb-pop .17s cubic-bezier(.23,1,.32,1)}@keyframes fb-pop{from{opacity:0;transform:scale(.96)}}
.fb-ctext{display:block;width:100%;min-height:96px;padding:14px;border:0;resize:vertical;outline:0;background:transparent;color:var(--plum);font-size:13.5px;line-height:1.5}.fb-ctext::placeholder{color:#aa9eac}.fb-ctext:focus{box-shadow:0 0 0 2px rgba(233,93,63,.18) inset}
.fb-cstatus{min-height:26px;padding:0 14px 9px;display:flex;align-items:center;gap:7px;color:var(--muted);font-size:11.5px}.fb-cstatus:empty{display:none}.fb-listen-dot{width:7px;height:7px;border-radius:50%;background:var(--persimmon);animation:fb-pulse 1.5s infinite}.fb-cresume{margin-left:auto;border:0;background:#f0e7f2;color:var(--plum);border-radius:999px;padding:5px 9px;font-size:11px;font-weight:650;cursor:pointer}
.fb-cfoot{display:flex;justify-content:flex-end;gap:8px;padding:9px 10px;border-top:1px solid var(--line)}.fb-ccancel{background:transparent}.fb-cadd{border:0;background:var(--persimmon);color:#fff;font-weight:700}.fb-cadd:hover{background:var(--persimmon-dark)}.fb-cadd:disabled{opacity:.45;cursor:default}
.fb-notice{position:fixed;left:50%;bottom:90px;z-index:4;transform:translateX(-50%);display:none;padding:8px 13px;border-radius:999px;background:rgba(43,27,46,.9);color:#fff;font-size:12px;box-shadow:0 8px 24px rgba(43,27,46,.22);pointer-events:none}
.fb-sheet{position:fixed;top:0;right:0;z-index:6;width:390px;max-width:92vw;height:100%;display:flex;visibility:hidden;flex-direction:column;background:var(--paper);border-left:1px solid var(--line);box-shadow:-18px 0 48px rgba(43,27,46,.13);pointer-events:auto;transform:translateX(102%);transition:transform .3s cubic-bezier(.23,1,.32,1),opacity .18s ease,visibility 0s linear .3s}.fb-sheet.open{visibility:visible;transform:none;transition-delay:0s}.fb-sheet.dim,.fb-sheet.yield{opacity:.14;pointer-events:none}
.fb-shead{display:flex;align-items:center;justify-content:space-between;padding:17px 18px;border-bottom:1px solid var(--line)}.fb-shead h2{margin:0;font-size:17px;letter-spacing:-.015em}.fb-sclose{border:0;background:transparent;color:#9b8f9e;font-size:17px;cursor:pointer}.fb-slist{flex:1;overflow:auto;padding:13px 14px;display:flex;flex-direction:column;gap:9px}.fb-empty{padding:4px;color:#9b8f9e;font-size:13px;line-height:1.5}
.fb-card{position:relative;padding:11px 36px 11px 26px;border:1px solid var(--line);border-radius:13px;background:#fff}.fb-card-region{background:#fcf8fd}.fb-card.dragging{opacity:.5;border-style:dashed;border-color:var(--persimmon)}.fb-grip{position:absolute;left:0;top:0;bottom:0;width:20px;display:grid;place-items:center;color:#c9bdca;cursor:grab}.fb-card-top{display:flex;align-items:center;gap:7px}.fb-badge{width:21px;height:21px;display:grid;place-items:center;border-radius:50%;background:var(--persimmon);color:#fff;font-size:10px;font-weight:700}.fb-input{font-size:9.5px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:#998b9c}.fb-comp{font-size:13.5px;font-weight:700;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.fb-src{display:inline-block;margin-top:6px;padding:2px 6px;border-radius:6px;background:#f0e7f2;color:#66506d;font:10.5px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;word-break:break-all}.fb-say{margin:7px -5px 0;padding:4px 5px;border-radius:6px;outline:0;color:var(--plum);font-size:13.5px;line-height:1.5;white-space:pre-wrap}.fb-say:hover{background:var(--cream)}.fb-say:focus{background:var(--cream);box-shadow:0 0 0 2px rgba(233,93,63,.18)}.fb-region-meta{margin-top:5px;color:#9b8f9e;font-size:11px}.fb-region-img{display:block;width:100%;max-height:150px;object-fit:cover;margin-top:8px;border-radius:9px;border:1px solid var(--line);animation:fb-thumb .16s cubic-bezier(.23,1,.32,1)}@keyframes fb-thumb{from{opacity:0;transform:scale(.96)}}.fb-components{margin-top:7px;color:#897b8d;font-size:11px;line-height:1.45}
.fb-del,.fb-edit{position:absolute;top:10px;border:0;background:transparent;color:#c6b9c8;cursor:pointer;padding:2px}.fb-del{right:10px}.fb-edit{right:30px}.fb-del:hover{color:var(--persimmon)}.fb-edit:hover{color:#76507f}
.fb-sfoot{padding:14px;border-top:1px solid var(--line);display:flex;flex-direction:column;gap:10px}.fb-copy{height:43px;border:0;border-radius:10px;background:var(--persimmon);color:#fff;font-weight:700;cursor:pointer}.fb-copy:hover{background:var(--persimmon-dark)}.fb-copy.done{background:var(--plum);animation:fb-count .2s ease}.fb-sfoot-row{display:flex;align-items:center;justify-content:space-between;gap:8px}.fb-resume{padding:8px 12px;border:1px solid var(--line);border-radius:8px;background:#f3edf4;color:var(--plum);font-size:12.5px;font-weight:650;cursor:pointer}.fb-discard{border:0;background:none;color:#9b8f9e;font-size:12px;text-decoration:underline;cursor:pointer}.fb-fallback{display:none;width:100%;height:110px;border:1px solid var(--line);border-radius:8px;padding:8px;font:11px ui-monospace,monospace}
.fb-toast{position:fixed;left:50%;bottom:31px;z-index:7;display:flex;align-items:center;gap:8px;padding:11px 16px;border-radius:11px;background:var(--plum);color:#fff;font-size:13px;box-shadow:0 14px 40px rgba(43,27,46,.35);opacity:0;pointer-events:none;transform:translateX(-50%) translateY(16px);transition:opacity .18s ease,transform .18s cubic-bezier(.23,1,.32,1)}.fb-toast.show{opacity:1;transform:translateX(-50%)}.fb-toast .ok{color:#ff9a87}
@media (prefers-reduced-motion:reduce){.fb-pin,.fb-composer.open,.fb-review-count.show,.fb-region-img,.fb-confirm-box,.fb-copy.done{animation:none!important}.fb-pill .fb-dot{animation:none!important}.fb-bubble:hover{transform:none}.fb-sheet{transition:opacity .18s ease}.fb-tip,.fb-toast{transition:opacity .15s ease}}
@media (prefers-reduced-transparency:reduce){.fb-pill,.fb-notice{background:var(--plum);backdrop-filter:none}}
@media (prefers-contrast:more){.fb-composer,.fb-card,.fb-sheet{border-color:var(--plum)}.fb-pill{border-color:#fff}}
.fb-region-img[hidden]{display:none}
.fb-composer{max-height:calc(100vh - 16px);overflow:auto}
.fb-pin{pointer-events:auto;cursor:pointer;padding:0}.fb-pin:focus-visible{outline:3px solid var(--plum);outline-offset:3px}
.fb-pin-preview{position:fixed;z-index:7;display:none;max-width:min(300px,calc(100vw - 24px));max-height:220px;overflow:hidden;white-space:pre-wrap;padding:12px 14px;border:1px solid var(--line);border-radius:12px;background:var(--paper);box-shadow:0 12px 36px rgba(43,27,46,.2);font-size:13px;line-height:1.5;pointer-events:none}.fb-pin-preview.show{display:block}
.fb-key-hint{margin-right:auto;align-self:center;max-width:110px;font-size:9px;line-height:1.4;color:var(--muted)}
.fb-toast{top:16px;bottom:auto;left:16px;max-width:calc(100vw - 32px);transform:translateY(-8px);visibility:hidden}.fb-toast.show{transform:none;visibility:visible;pointer-events:auto}.fb-toast button{border:0;border-radius:6px;padding:5px 8px;background:var(--cream);color:var(--plum);font:inherit;cursor:pointer}.fb-toast button[hidden]{display:none}
`
